<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
<head>
  <title>ACM Contest Manager</title>
  <link rel="stylesheet" type="text/css" href="style.css" />
  <script src="acm.js" type="text/javascript"></script>
</head>
<body id="document">
<div id="MenuLinks">
<ul> 
 <li><a href="scoreboard.php?id=<?php echo $_GET["id"]; ?>"> Scoreboard</a></li> 
<!-- <li><a href="clarifications.php?id=<?php echo $_GET["id"]; ?>">Clarifications</a></li> -->
<li><a href="problems.php?id=<?php echo $_GET["id"]; ?>">Problems</a></li>
</ul>
</div>
<hr />
